# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-19 12:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nberRecep', models.CharField(max_length=20, null=True)),
                ('nberCni', models.CharField(max_length=9, null=True)),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('birthdate', models.CharField(max_length=10)),
                ('status', models.CharField(default='fail', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PoliceStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=50)),
                ('lat', models.CharField(max_length=10)),
                ('long', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='cni',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cniBasic.PoliceStation'),
        ),
    ]
