# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-19 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cniBasic', '0002_auto_20180319_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cni',
            name='nberCni',
            field=models.CharField(max_length=9, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='recep',
            name='nberRecep',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
