# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-19 12:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cniBasic', '0003_auto_20180319_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cni',
            name='status',
        ),
        migrations.RemoveField(
            model_name='recep',
            name='status',
        ),
    ]
