# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-19 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cniBasic', '0004_auto_20180319_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cni',
            name='nberCni',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
